clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: klakegg/hugo:0.111.3-ext-ubuntu
    commands:
      - hugo --minify
    when:
      event: [ push, pull_request ]
      branch: [ main, feature/*, renovate/* ]
  publish:
    image: alpine
    secrets: [ ssh_key ]
    commands:
      - apk add rsync openssh-client
      - eval `ssh-agent -s`
      - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
      - rsync -e "ssh -o StrictHostKeyChecking=no" -r ./public/* vylpes@192.168.1.115:/home/vylpes/apps/website
    when:
      event: push
      branch: [ main ]