clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: klakegg/hugo:0.111.3-ext-ubuntu
    commands:
      - hugo --minify
    when:
      event: [ push, pull_request ]
      branch: [ main, feature/*, renovate/* ]
  publish:
    image: secoresearch/rsync
    secrets: [ ssh_key, ssh_known_hosts ]
    environment:
      HOME: /tmp/woodpecker
      SSH_PRIVATE_KEY: "$SSH_KEY"
      SSH_KNOWN_HOSTS: "$SSH_KNOWN_HOSTS"
      RSYNC_SOURCE: public/
      RSYNC_TARGET: vylpes@192.168.68.120:/home/vylpes/apps/website
      RSYNC_OPTIONS: -avz --delete
    when:
      event: push
      branch: [ main ]