name: Deploy To Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Hugo
      uses: https://github.com/peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.87.0'
    - name: Build Hugo
      run: hugo --minify
    - name: Copy Files To Location
      run: cp -r ./public ${{ secrets.PROD_REPO_PATH }}