name: Deploy To Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Hugo
      uses: https://github.com/peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.87.0'
        extended: true
    - name: Build Hugo
      run: hugo
    - name: Copy Files To Location
      run: rsync -rvzP --delete ./public/* ${{ secrets.PROD_REPO_PATH }}