name: Test

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - renovate/*

jobs:
  build:
    runs-on: node

    steps:
    - uses: actions/checkout@v4
    - name: Setup Hugo
      uses: https://github.com/peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.87.0'
        extended: true
    - name: Build Hugo
      run: hugo